version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/bradhe/hobo
    steps:
      - checkout
      - run:
          name: Run tests
          command: make test
  deploy:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/bradhe/hobo
    steps:
      - checkout
      - setup_remote_docker
      - run: make image
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: docker push bradhe/hobo:latest
workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
